name: Build and Upload

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@main
        with:
          lfs: true
      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_ONLY: true
       
  build_and_deploy:   
    name: build static website
    runs-on: ubuntu-latest
    if: github.repository_owner == 'rahel-a' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@main
        with:
          lfs: true
      - name: "Build and deploy website"
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
