name: Build and Upload

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@main
        with:
          lfs: true
      - name: Install rust tools
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
      - name: Check CV build
        run: cd content/cv/ && cargo check --target wasm32-unknown-unknown

      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      - name: Build cv webpage
        run: cd content/cv/ && trunk build

      - name: Build only 
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          BUILD_ONLY: true
       
  build_and_deploy:   
    name: build static website
    runs-on: ubuntu-latest
    if: github.repository_owner == 'rahel-a' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout main
        uses: actions/checkout@main
        with:
          lfs: true
      - name: Install rust tools
        uses: dtolnay/rust-toolchain@stable
        with:
          target: wasm32-unknown-unknown
      - name: Install trunk
        uses: jetli/trunk-action@v0.4.0
        with:
          version: 'latest'
      - name: Build CV webpage
        run: cd content/cv/ && trunk build --release
      - name: Add CV webpage to static
        run: cp content/cv/dist static/cv

      - name: "Build and deploy website"
        uses: shalzz/zola-deploy-action@v0.18.0
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
